### ISSUE TITLE
not with context

### ISSUE THREAD

**Issue by zarigata** [aminblm/linkedin-apply-bot#1]
so everytime i start it gives me this error 
`(venv) K:\_____ PYTHON ______\LINKEDIN_APLY\2\linkedin-apply-bot>python test.py
Traceback (most recent call last):
  File "K:\_____ PYTHON ______\LINKEDIN_APLY\2\linkedin-apply-bot\test.py", line 6, in <module>
    from utils import prGreen,prRed,prYellow
  File "K:\_____ PYTHON ______\LINKEDIN_APLY\2\linkedin-apply-bot\utils.py", line 112
    match job.casefold():`

dont know why but even the test is doing this

**Comment by aminblm** [comment]
normally should be working

Did you run it using Python 3.10?
